name: Daily build

on:
  push:

jobs:
  generate_php_versions:
    uses: ./.github/workflows/generate_php_versions.yml
    with:
      ignore_versions: '["8.1"]'
  mixin:
    needs: generate_php_versions
    uses: ./.github/workflows/mixin.yml
    with:
      base_json: ${{ needs.generate_php_versions.outputs.values }}
      mixin_yaml: |
        - variant: ""
          configure_append: ""
          optimize_options_c_cpp: "-O2"
          optimize_options_ld: "-O1"
        - variant: "-debug"
          configure_append: "--enable-debug"
          optimize_options_c_cpp: "-O0"
          optimize_options_ld: "-O0"
        - variant: "-opt"
          configure_append: ""
          optimize_options_c_cpp: "-O3"
          optimize_options_ld: "-O2"
  result:
    needs: mixin
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ needs.mixin.outputs.values }}"
