name: Mixin

on:
  workflow_call:
    inputs:
      base_json:
        type: string
        required: true
      mixin_yaml:
        type: string
        required: true
    outputs:
      values:
        description: "Result"
        value: ${{ jobs.mixin.outputs.values }}

jobs:
  mixin:
    runs-on: ubuntu-latest
    steps:
      - id: mixin
        run: |
          echo "${{ inputs.mixin_yaml }}" | yq -o=json > "mixin.json"
          echo "${{ inputs.base_json }}" > "base.json"
          jq --argjson "mixin" "$(cat "mixin.json")" '[.[] | $mixin[] as $y | . + $y]' "base.json"
          echo values=$(jq --argjson "mixin" "$(cat "mixin.json")" '[.[] | $mixin[] as $y | . + $y]' "base.json") >> $GITHUB_OUTPUT
    outputs:
      values: ${{ steps.mixin.outputs.values }}
