name: Conga

on:
  workflow_call:
    inputs:
      directories:
        required: true
        type: string
      foo:
        required: true
        type: string

jobs:
  conga:
    runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4
