name: Conga

on:
  workflow_call:
    inputs:
      directories:
        required: true
        type: string
      foo:
        required: true
        type: string

jobs:
  conga:
    name: pongo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: ${{ fromJson(inputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: qongo
        working-directory: ${{ matrix.directories }}
        run: |
          echo "$(pwd) | ${{ inputs.foo }}"
