name: Build image

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "values=foo${{ !startsWith(github.ref, 'refs/tags/') && ',bar' || '' }}"
