name: Build image

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first
        id: first
        run: |
          echo "full=\"$(uname -a)\"" >> $GITHUB_OUTPUT
          echo "short=\"$(whoami)\"" >> $GITHUB_OUTPUT
      - name: second
        run: |
          echo "${{ steps.first.outputs.full }}${{ !startsWith(github.ref, 'refs/tags/') && format(',{0}', steps.first.outputs.short) || '' }}"
