name: Test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ["bongo", "conga"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get variants directories
        id: variants
        run: |
          echo "directories=$(ls -d variants/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      variant_directories: ${{ steps.variants.outputs.directories }}
      matrix: ${{ toJson(matrix) }}
  second:
    needs: first
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ${{ fromJson(needs.first.outputs.foo) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: BONGO
        working-directory: ${{ matrix.directory }}
        run: |
          echo "${{ matrix.foo }}"
