name: Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      variant_directories: ${{ steps.variants.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get variants directories
        id: variants
        run: |
          echo "directories=$(ls -d variants/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  second:
    needs: first
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.first.outputs.variant_directories) }}
    steps:
      - name: BONGO ${{ matrix.directory }}
        working-directory: "variants/${{ matrix.directory }}"
        run: |
          ls -al
