name: Test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Generate matrix
        id: generate_matrix
        env:
          gm_foo: '["bongo", "conga"]'
          gm_bar: '["qongo", "dongo"]'
        run: |
          printenv | grep -E '^gm_' | sed 's/^gm_//g' >> $GITHUB_OUTPUT
    outputs:
      foo: ${{ steps.generate_matrix.foo }}
      bar: ${{ steps.generate_matrix.bar }}
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Describe
        id: describe
        run: |
          echo "directories=$(ls -d variants/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      directories: ${{ steps.describe.outputs.directories }}
  test:
    needs: ["first", "second"]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.first.outputs.foo }}"
          echo "${{ needs.first.outputs.bar }}"
          echo "${{ needs.second.outputs.directories }}"
  # third:
  #   needs: ["first", "second"]
  #   uses: ./.github/workflows/reuse.yml
  #   with:
  #     foo: ${{ needs.first.outputs.foo }}
  #     bar: ${{ needs.first.outputs.bar }}
  #     directories: ${{ needs.second.outputs.directories }}
