name: Build image

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          export BONGO="baz"
          echo "values=foo${{ !startsWith(github.ref, 'refs/tags/') && format(',{0}', env.BONGO) || '' }}"
