name: Test2

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    
    steps:
      - name: Get all versions
        run: |
          versions='${{ toJson(matrix.version) }}'
          echo "All versions: $versions"
