name: Build image

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Debian version
        id: debian_version
        run: |
          echo "id=$(docker run --rm -i "ghcr.io/distroless-php/image:8.2-opt-base" sh -c '. /etc/os-release && echo ${VERSION_ID}')" >> $GITHUB_OUTPUT
      - name: bongo
        run: |
          echo "${{ steps.debian_version.outputs.id }}"
