name: Test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Generate matrix
        id: generate_matrix
        env:
          _gm_foo: '["bongo", "conga"]'
          _gm_bar: '["qongo", "dongo"]'
        run: |
          echo "values=$(printenv | grep '^_gm_' | sed 's/^_gm_//' | jq -R 'split("=") | {(.[0]): .[1]}' | jq -s -c 'add')" >> $GITHUB_OUTPUT
    outputs:
      values: ${{ steps.generate_matrix.outputs.values }}
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Describe
        id: describe
        run: |
          echo "directories=$(ls -d variants/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      directories: ${{ steps.describe.outputs.directories }}
  third:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants: [1, 2, 3, 4, 5]
    steps:
      - run: |
          echo "${{ matrix.variants }}" > "output_${{ matrix.variants }}.txt"
  fourth:
    needs: third
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat output_*.txt
  fifth:
    needs: ["first", "second"]
    uses: ./.github/workflows/reuse.yml
    with:
      foo: ${{ fromJson(needs.first.outputs.values).foo }}
      bar: ${{ fromJson(needs.first.outputs.values).bar }}
      directories: ${{ needs.second.outputs.directories }}
