name: Test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ["bongo", "conga"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Describe
        id: describe
        env:
          MATRIX: ${{ toJson(matrix) }}
        run: |
          echo "${MATRIX}" | jq -c .
          echo "directories=$(ls -d variants/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo "matrix=$(echo "${MATRIX}" | jq -c .)" >> $GITHUB_OUTPUT
    outputs:
      variant_directories: ${{ steps.describe.outputs.directories }}
      foo: ${{ steps.describe.outputs.matrix }}
  second:
    needs: first
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        foo: ${{ fromJson(needs.first.outputs.foo) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: BONGO
        run: |
          echo "${{ matrix.foo }}"
